### Site metadata ###
strict_front_matter: true
permalink: /blog/:categories/:year/:month/:day/:title.html
repository: rpunt/rpunt.github.io
author: Ryan Punt
google_analytics: G-6N84X0RZC6

### Build settings ###

url: https://mirum.org
baseurl: ""

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
